/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "gpio.h"
#include "rcc.h"
#include "exti.h"
#include "nvic.h"




int main(void)
{
	/* CLOCK ACMA */
	RCC_GPIO_ClockEnable(GPIOA);
	RCC_GPIO_ClockEnable(GPIOC);

	GPIO_Config_t LedAyarla = {
		.pin = 5,
		.mode = GPIO_MODE_OUTPUT,
		.otype = GPIO_OTYPE_PP,
		.speed = GPIO_SPEED_LOW,
		.pupd = GPIO_PUPD_NONE

	};

	GPIO_Config_t ButonAyarla = {
			.pin = 13,
			.mode = GPIO_MODE_INPUT,
			.otype = GPIO_OTYPE_PP,
			.speed = GPIO_SPEED_LOW,
			.pupd = GPIO_PUPD_NONE

		};

	GPIO_Init(GPIOA,&LedAyarla);
	GPIO_Init(GPIOC,&ButonAyarla);


	/* INTERRUPT */

	EXTI_Config_t KesmeConfig = {
			.port = GPIOC,
			.pin = 13,
			.trigger = EXTI_TRIGGER_FALLING
	};


	EXTI_Init(&KesmeConfig);
	NVIC_EnableIRQ(EXTI15_10_IRQn);


	for(;;){
		// interrupt-driven çalışıyoruz, burada hiçbir şey yapmamıza gerek yok
	}

}

void EXTI15_10_IRQHandler(void){
	if (EXTI_GetPending(13)){
		GPIO_TogglePin(GPIOA,5);
		EXTI_ClearPending(13);
	}
}
